version: '3.1'
services:

    api:
        build:
            context: ../
            dockerfile: ./development/Dockerfile
        container_name: ccvs_api
        command: make run
        depends_on:
            - postgres
        env_file:
            - docker.env
        external_links:
            - anchore_engine
            - clair_clair
            - trivy_wrapper
        networks:
            - ccvs_net
        ports:
            - "8000:8000"
            - "8001:8001"
        volumes:
            - "../:/app"

    worker:
        build:
            context: ../
            dockerfile: ./development/Dockerfile
        container_name: ccvs_worker
        command: make run-celery
        depends_on:
            - postgres
        env_file:
            - docker.env
        external_links:
            - anchore_engine
            - clair_clair
            - trivy_wrapper
        networks:
            - ccvs_net
        volumes:
            - "../:/app"

    postgres:
        container_name: ccvs_pgdb
        environment:
            POSTGRES_DB: ccvs
            POSTGRES_USER: ccvsuser
            POSTGRES_PASSWORD: ccvspwd
        image: "postgres:9.6-alpine"
        networks:
            - ccvs_net
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - "postgres_vol:/var/lib/postgresql/data/"

volumes:
    postgres_vol:

networks:
    ccvs_net:
