# Generated by Django 2.1.7 on 2019-03-12 15:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('container_scanning', '0002_auto_20190304_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
