# Generated by Django 2.1.7 on 2019-07-10 14:53
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_scanning', '0003_auto_20190312_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='url',
        ),
    ]
