# Generated by Django 3.0.1 on 2020-01-07 17:35
import uuid

import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('container_scanning', '0004_remove_vendor_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4, editable=False,
                    primary_key=True, serialize=False)),
                ('type', models.CharField(
                    choices=[('scan_image', 'scan_image')],
                    max_length=20)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'pending'),
                        ('started', 'started'),
                        ('finished', 'finished'),
                        ('failed', 'failed')],
                    default='pending',
                    max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('result',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        null=True)),
            ],
        ),
    ]
