# Generated by Django 3.0.5 on 2020-04-14 15:36

import uuid

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_scanning', '0006_auto_20200114_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('started', 'started'), (
                    'finished', 'finished'), ('failed', 'failed')], default='pending', max_length=20)),
                ('result', models.CharField(choices=[
                 ('passed', 'passed'), ('failed', 'failed')], default=None, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vulnerabilities', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('vendors', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
