# Generated by Django 3.0.1 on 2020-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_scanning', '0007_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='image',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
