# Generated by Django 3.0.1 on 2020-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_scanning', '0008_analysis_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='result',
            field=models.CharField(choices=[('pending', 'pending'), ('passed', 'passed'), (
                'failed', 'failed')], default='pending', max_length=20),
        ),
    ]
