# Generated by Django 3.0.5 on 2020-04-29 13:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_scanning', '0009_auto_20200414_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='analysis',
            name='whitelist',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
