# Generated by Django 3.0.5 on 2020-04-29 20:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_scanning', '0010_auto_20200429_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='vendors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='vulnerabilities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='whitelist',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
