# Generated by Django 2.1.7 on 2019-03-04 14:12
import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageVendor',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('vendor_image_internal_id', models.CharField(max_length=200)),
                ('image', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='container_scannning.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('credentials',
                 django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='imagevendor',
            name='vendor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='container_scannning.Vendor'),
        ),
        migrations.AddField(
            model_name='image',
            name='vendors',
            field=models.ManyToManyField(
                through='container_scannning.ImageVendor',
                to='container_scannning.Vendor'),
        ),
    ]
